### ISSUE TITLE
Winston: Update Backend to serve agreed upon structure

### ISSUE THREAD

**Issue by jameswinegar** [winlinworks/fairbnb#18]
- [ ] Update DB and API with the id, name, tagline, location, image, and price fields for listings (see #14):
{
    id: 2,
    name: "property-2",
    tagline: "this is property 2",
    location: "Houston, TX",
    image:
      "https://a0.muscache.com/im/pictures/2f53e928-a91e-464c-b69f-14eff28a3b85.jpg?im_w=960",
    price: 263,
}

**Comment by winlinworks** [comment]
@unnamedsunshine are you good with the above requirements for the listings fields?

**Comment by unnamedsunshine** [comment]
Yes. looks good!
