### ISSUE TITLE
FastAPI PUT listing not function as planned

### ISSUE THREAD

**Issue by unnamedsunshine** [winlinworks/fairbnb#27]
`curl -X 'PUT' \
  'http://localhost:8000/listings/3' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "string",
  "tagline": "string",
  "location": "string",
  "image": "https://a0.muscache.com/im/pictures/d1db0b4a-9830-42e2-875d-0d41820ca4e3.jpg?im_w=960",
  "price": 0,
  "id": 3,
  "owner_id": 1
}'`

`backend  | ERROR:    Exception in ASGI application
backend  | Traceback (most recent call last):
backend  |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
backend  |     result = await app(  # type: ignore[func-returns-value]
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
backend  |     return await self.app(scope, receive, send)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
backend  |     await super().__call__(scope, receive, send)
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
backend  |     await self.middleware_stack(scope, receive, send)
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
backend  |     raise exc
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
backend  |     await self.app(scope, receive, _send)
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
backend  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
backend  |     raise exc
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
backend  |     await app(scope, receive, sender)
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
backend  |     await self.middleware_stack(scope, receive, send)
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
backend  |     await route.handle(scope, receive, send)
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
backend  |     await self.app(scope, receive, send)
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
backend  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
backend  |     raise exc
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
backend  |     await app(scope, receive, sender)
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
backend  |     response = await f(request)
backend  |                ^^^^^^^^^^^^^^^^
backend  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
backend  |     raw_response = await run_endpoint_function(
backend  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
backend  |     return await run_in_threadpool(dependant.call, **values)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/app/.venv/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
backend  |     return await anyio.to_thread.run_sync(func, *args)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/app/.venv/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
backend  |     return await get_async_backend().run_sync_in_worker_thread(
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/app/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
backend  |     return await future
backend  |            ^^^^^^^^^^^^
backend  |   File "/app/.venv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
backend  |     result = context.run(func, *args)
backend  |              ^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/app/src/main.py", line 113, in put_listing
backend  |     return update_listing(db, listing_id, listing)
backend  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend  |   File "/app/src/crud.py", line 78, in update_listing
backend  |     update_record(db_listing, new_listing_data)
backend  |   File "/app/src/utils.py", line 14, in update_record
backend  |     setattr(db_record, key, value)
backend  | AttributeError: 'NoneType' object has no attribute 'name'`

**Comment by winlinworks** [comment]
@unnamedsunshine see #26, I'll close this one
